// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TinPro.Models;

#nullable disable

namespace TinPro.Migrations
{
    [DbContext(typeof(MYcontext))]
    partial class MYcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("BeesOnTrip", b =>
                {
                    b.Property<int>("Id_Bee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_Trip")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_Bee", "Id_Trip");

                    b.HasIndex("Id_Trip");

                    b.ToTable("BeesOnTrip");
                });

            modelBuilder.Entity("PlacesOnTrip", b =>
                {
                    b.Property<int>("Id_Trip")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_Place")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_Trip", "Id_Place");

                    b.HasIndex("Id_Place");

                    b.ToTable("PlacesOnTrip");
                });

            modelBuilder.Entity("TinPro.Models.Bee", b =>
                {
                    b.Property<int>("Id_Bee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Bee");

                    b.HasIndex("Id_Role");

                    b.ToTable("Bees");
                });

            modelBuilder.Entity("TinPro.Models.Place", b =>
                {
                    b.Property<int>("Id_Place")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Place");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("TinPro.Models.Role", b =>
                {
                    b.Property<int>("Id_Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Role");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TinPro.Models.Trip", b =>
                {
                    b.Property<int>("Id_Trip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Trip");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("BeesOnTrip", b =>
                {
                    b.HasOne("TinPro.Models.Bee", null)
                        .WithMany()
                        .HasForeignKey("Id_Bee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TinPro.Models.Trip", null)
                        .WithMany()
                        .HasForeignKey("Id_Trip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlacesOnTrip", b =>
                {
                    b.HasOne("TinPro.Models.Place", null)
                        .WithMany()
                        .HasForeignKey("Id_Place")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TinPro.Models.Trip", null)
                        .WithMany()
                        .HasForeignKey("Id_Trip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TinPro.Models.Bee", b =>
                {
                    b.HasOne("TinPro.Models.Role", "Role")
                        .WithMany("Bees")
                        .HasForeignKey("Id_Role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TinPro.Models.Role", b =>
                {
                    b.Navigation("Bees");
                });
#pragma warning restore 612, 618
        }
    }
}
